image: busybox:latest

stages:
  - test

before_script:
  - echo "Before script section"

after_script:
  - echo "After script section"

test:
  stage: test
  image: registry.govcloud.futures.army/tac-federal-apple/containers/with-dod-certs/node:16
  tags:
    - gitlab-runner
  script:
    - ./test/run-all-tests.sh
  artifacts:
    paths:
      - 'test/logs/*.log'
