image: node:latest

stages:
  - test

variables:
  TERM: linux

before_script:
  - yarn install --ignore-scripts

after_script:
  - echo "After script section"

test:
  stage: test
  tags:
    - linux
  script:
    - git --version
    - git config user.email "git-hooks-runner@some.place"
    - git config user.name "git-hooks-runner"
    - yarn install
    - cd test
    - ./run-all-tests.sh
  artifacts:
    when: always
    paths:
      - 'test/logs/*.log'
