#!/usr/bin/env bash

. "$(dirname "$0")/utilities/log-message.sh"

. "$(dirname "$0")/_/husky.sh"

log_message "INFORMATIONAL" "-----------------------COMMIT-----------------------"

npx --no-install commitlint --edit "$1"
