#!/usr/bin/env bash

# This could be a call to `source log-message.sh`... should it?
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
LIME_YELLOW=$(tput setaf 190)
BLUE=$(tput setaf 4)
BRIGHT=$(tput bold)
NORMAL=$(tput sgr0)
REVERSE=$(tput smso)
UNDERLINE=$(tput smul)

log_message(){
  SEVERITY=$1
  MESSAGE=$2
  SEVERITY_COLOR=$NORMAL
  case $SEVERITY in
  EMERGENCY) SEVERITY_COLOR=$RED$REVERSE ;;
  ALERT) SEVERITY_COLOR=$RED$UNDERLINE ;;
  CRITICAL) SEVERITY_COLOR=$RED$BRIGHT ;;
  ERROR) SEVERITY_COLOR=$RED ;;
  WARNING) SEVERITY_COLOR=$YELLOW ;;
  NOTICE) SEVERITY_COLOR=$LIME_YELLOW ;;
  INFORMATIONAL) SEVERITY_COLOR=$GREEN ;;
  DEBUG) SEVERITY_COLOR=$BLUE ;;
  *) SEVERITY_COLOR=$CHGME;;
  esac

  printf "${SEVERITY_COLOR}%s - %s${NORMAL}\n" "$SEVERITY" "$MESSAGE"
}

. "$(dirname "$0")/_/husky.sh"

GREEN=$(tput setaf 2)
NORMAL=$(tput sgr0)

log_message "INFORMATIONAL" "-----------------------COMMIT-----------------------"

npx --no-install commitlint --edit "$1"
