#!/usr/bin/env bash

. "$(dirname "$0")/_/husky.sh"

GREEN=$(tput setaf 2)
NORMAL=$(tput sgr0)

echo "${GREEN}-----------------------COMMIT-----------------------${NORMAL}"

npx --no-install commitlint --edit "$1"
