#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

#exec >/dev/tty 2>&1
exec < /dev/tty

FRONTEND_DIRECTORY="test" # TODO - Make this your real frontend directory
BACKEND_DIRECTORY="test" # TODO - Make this your real backend directory

GREEN='\033[0;32m'
RED='\033[0;31m'
NOCOLOR='\033[0m'
echo "${GREEN}----------------------PRE-PUSH----------------------${NOCOLOR}"

REMOTE_SHA=$(git rev-parse origin/HEAD)

if [ "$(git symbolic-ref HEAD)" = "refs/heads/main" ]; then
  pwd
  frontend_files_changed=$(git diff --name-only "$REMOTE_SHA" HEAD | grep -e ^"$FRONTEND_DIRECTORY" | wc -l)
  printf "INFO - Frontend file delta: %d" "$frontend_files_changed"
  backend_files_changed=$(git diff --name-only "$REMOTE_SHA" HEAD | grep -e ^"$BACKEND_DIRECTORY" -e build.gradle | wc -l)
  printf "INFO - Backend file delta: %d" "$frontend_files_changed"
  if [ "$frontend_files_changed" -gt 0 ]; then
    echo "${GREEN}Running frontend tests${NOCOLOR}"
    echo "${RED}ERROR - Put your frontend test logic here. (e.g., 'CI=true yarn test')${RED}"
    echo "${GREEN}Running frontend build${NOCOLOR}"
    echo "${RED}ERROR - Put your frontend build logic here. (e.g., 'yarn build')${RED}"
  else
    echo "${RED}No changes made to frontend - SKIPPING TESTS${NOCOLOR}"
  fi
  if [ "$backend_files_changed" -gt 0 ]; then
    echo "${GREEN}Running backend tests${NOCOLOR}"
    echo "${RED}TODO - Put your backend test logic here. (e.g., 'CI=true ./gradlew test)${NOCOLOR}"
  else
    echo "${RED}No changes made to backend - SKIPPING TESTS${NOCOLOR}"
  fi
fi

#./scripts/run-journey-test.sh
