#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

GREEN='\033[0;32m'
NOCOLOR='\033[0m'

echo "${GREEN}---------------------PRE-COMMIT---------------------${NOCOLOR}"

yarn lint-staged --verbose --config .lintstagedrc.json
