#!/usr/bin/env sh

. "$(dirname "$0")/utilities/log-message.sh"

. "$(dirname -- "$0")/_/husky.sh"
log_message "INFORMATIONAL" "---------------------PRE-COMMIT---------------------"

yarn lint-staged --verbose --config .lintstagedrc.json
