#!/usr/bin/env bash

# This could be a call to `source log-message.sh`... should it?
RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
LIME_YELLOW=$(tput setaf 190)
BLUE=$(tput setaf 4)
BRIGHT=$(tput bold)
NORMAL=$(tput sgr0)
REVERSE=$(tput smso)
UNDERLINE=$(tput smul)

log_message(){
  SEVERITY=$1
  MESSAGE=$2
  SEVERITY_COLOR=$NORMAL
  case $SEVERITY in
  EMERGENCY) SEVERITY_COLOR=$RED$REVERSE ;;
  ALERT) SEVERITY_COLOR=$RED$UNDERLINE ;;
  CRITICAL) SEVERITY_COLOR=$RED$BRIGHT ;;
  ERROR) SEVERITY_COLOR=$RED ;;
  WARNING) SEVERITY_COLOR=$YELLOW ;;
  NOTICE) SEVERITY_COLOR=$LIME_YELLOW ;;
  INFORMATIONAL) SEVERITY_COLOR=$GREEN ;;
  DEBUG) SEVERITY_COLOR=$BLUE ;;
  *) SEVERITY_COLOR=$CHGME;;
  esac

  printf "${SEVERITY_COLOR}%s - %s${NORMAL}\n" "$SEVERITY" "$MESSAGE"
}

source "$(dirname "$0")/_/husky.sh"

updateCommitMessage(){
  log_message "DEBUG" "Prepending issue number to commit message."
  if [ -n "$BRANCH_NAME" ]; then
  sed -i.bak -e "1s/^/$EXTRACTED_ISSUE_ID: /" "$1" # Prepend trimmed branch ID to the commit message
  fi
}

askUserToContinue(){
  exec < /dev/tty
  read -p "$(log_message "NOTICE" "Commit anyway? [y/n]")" -n 1 -r
  echo
  [[ $REPLY =~ ^[Yy]$ ]] && exit 0 || exit 1
}

printIssueURL(){
  log_message "NOTICE" "View on Pivotal Tracker: https://www.pivotaltracker.com/story/show/$EXTRACTED_ISSUE_ID"
}

doesInputMatchIssueFormat(){
  [[ "$1" =~ $2 ]]
}

handleInputMismatch(){
  log_message "ERROR" "Could not detect issue number from filtered input of '$1'"
  log_message "ERROR" "Branch name did not match regular expression $ISSUE_ID_FORMAT"
  askUserToContinue "$@"
}

ISSUE_ID_FORMAT="^([0-9]{9})$" # Pivotal Tracker Issue IDs are 9-digits

log_message "INFORMATIONAL" "-----------------PREPARE-COMMIT-MSG-----------------"
if git symbolic-ref --short HEAD 1>/dev/null 2>&1; then
  BRANCH_NAME="$(git symbolic-ref --short HEAD)"
else
  log_message "DEBUG" "Could not detect branch name, a rebase is probably in-progress."
  exit 0
fi

EXTRACTED_ISSUE_ID=$(echo "$BRANCH_NAME" | cut -d'-' -f1) # Get the first part of the branch name, delimited by '-'

CURRENT_COMMIT_MESSAGE=$(cut -sd':' -f1 < "$1")

if ! doesInputMatchIssueFormat "$EXTRACTED_ISSUE_ID" "$ISSUE_ID_FORMAT"; then
  handleInputMismatch "$EXTRACTED_ISSUE_ID"
fi

if doesInputMatchIssueFormat "$CURRENT_COMMIT_MESSAGE" "$ISSUE_ID_FORMAT"; then
  log_message "WARNING" "Issue number already present in commit message. Detected '$CURRENT_COMMIT_MESSAGE'."
  log_message "INFORMATIONAL" "Skipping auto-prepend."
  printIssueURL "$@"
  exit 0
elif [ -z "$CURRENT_COMMIT_MESSAGE" ]; then
  updateCommitMessage "$@"
  printIssueURL "$@"
else
  handleInputMismatch "$CURRENT_COMMIT_MESSAGE"
fi
