#!/usr/bin/env bash

source ../scripts/parse-arguments.sh > test-prepare-commit-msg.txt

expect << EOF
spawn bash ../hooks/prepare-commit-msg test-prepare-commit-msg.txt

expect {
  "INFO - Commit anyway?" {send "y\r";interact}
}
EOF
